### ISSUE TITLE
ใบอนุญาตผู้ปกครอง

### ISSUE THREAD

**Issue by somemer** [KMITL-PreElec9/Website#9]
![image](https://user-images.githubusercontent.com/84960447/121869565-60219200-cd2c-11eb-8547-6d66abad1a0c.png)

**Comment by Knapoj-01** [comment]
@SpedyNo1 ปัญหานี้เราคิดว่ามันดึงฟอนต์มาจาก Google แค่ส่วนบนส่วนเดียว แล้วที่เหลือมันไปหาฟอนต์ในเครื่องไบร์ท ซึ่งมันไม่มี ก็เลยเป็นบั๊กอย่างที่เห็น

**Comment by SpedyNo1** [comment]
done

**Comment by Knapoj-01** [comment]
ยังไม่โอเคน้าา ตอนนี้เราเอาโค๊ดของเก่ามาใช้อยู่
